version: '2'
services:
    dishservice-app:
        image: dishservice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dishservice-postgresql:5432/dishservice
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    dishservice-postgresql:
        extends:
            file: postgresql.yml
            service: dishservice-postgresql
